# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kurisu
email: kurisubrooks@gmail.com
description: >
    Kurisu Brooks: My home for Projects, Code, Design, and more.
twitter_username: kurisubrooks
github_username:  kurisubrooks
timezone: Australia/Sydney

# Build settings
markdown: kramdown

# Global settings
#port: 3000
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kurisubrooks.com" # the base hostname & protocol for your site
